# Generated by Django 4.2.7 on 2024-02-19 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('password_reset_notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresetrequest',
            options={'verbose_name': 'Запрос от пользователя на сброс', 'verbose_name_plural': 'Запросы от пользователей на сброс'},
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса'),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email пользователя'),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтверждение'),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
