# Generated by Django 4.2.7 on 2024-02-17 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='noname', max_length=255, verbose_name='Название')),
                ('description', models.CharField(default='Клиент', max_length=255, verbose_name='Описание')),
                ('user_link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='DrivingAxle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='noname', max_length=255, verbose_name='Название')),
                ('description', models.CharField(default='Модель ведущего моста', max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель ведущего моста',
                'verbose_name_plural': 'Модель ведущих мостов',
            },
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='noname', max_length=255, verbose_name='Название')),
                ('description', models.CharField(default='Модель двигателя', max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель двигателя',
                'verbose_name_plural': 'Модель двигателей',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='noname', max_length=255, verbose_name='Название')),
                ('description', models.CharField(default='Модель техники', max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель техники',
                'verbose_name_plural': 'Модель техники',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_machine', models.CharField(max_length=255, unique=True, verbose_name='Заводский номер машины')),
                ('number_engine', models.CharField(max_length=255, verbose_name='Заводской номер двигателя')),
                ('number_transmission', models.CharField(max_length=255, verbose_name='Заводской номер трансмиссии')),
                ('number_driving_axle', models.CharField(max_length=255, verbose_name='Заводской номер ведущего моста')),
                ('number_steering_axle', models.CharField(max_length=255, verbose_name='Заводской номер управляемого моста')),
                ('supply_contract', models.CharField(max_length=255, verbose_name='Договор поставки (номер, дата)')),
                ('shipment_date', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('end_consumer', models.CharField(max_length=255, verbose_name='Грузополучатель (конечный потребитель)')),
                ('shipping_address', models.CharField(max_length=255, verbose_name='Адрес поставки (эксплуатации)')),
                ('options', models.TextField(default='Стандарт', max_length=1000, verbose_name='Комплектация (дополнительные опции)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_book.client', verbose_name='Клиент')),
                ('model_driving_axle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_book.drivingaxle', verbose_name='Модель ведущего моста')),
                ('model_engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines_engine', to='service_book.engine', verbose_name='Модель двигателя')),
                ('model_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines_equipment', to='service_book.equipment', verbose_name='Модель техники')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='noname', max_length=255, verbose_name='Название')),
                ('description', models.CharField(default='Организация выполняющая ТО', max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Организация, проводившая ТО',
                'verbose_name_plural': 'Организации, проводившие ТО',
            },
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='noname', max_length=255, verbose_name='Название')),
                ('description', models.CharField(default='Способ восстановления', max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Способ восстановления',
                'verbose_name_plural': 'Способы восстановлений',
            },
        ),
        migrations.CreateModel(
            name='RefusalNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='noname', max_length=255, verbose_name='Название')),
                ('description', models.CharField(default='Узел отказа', max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Узел отказа',
                'verbose_name_plural': 'Узлы отказов',
            },
        ),
        migrations.CreateModel(
            name='SteeringAxle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='noname', max_length=255, verbose_name='Название')),
                ('description', models.CharField(default='Модель управляемого моста', max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель управляемого моста',
                'verbose_name_plural': 'Модель управляемых мостов',
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='noname', max_length=255, verbose_name='Название')),
                ('description', models.CharField(default='Модель трансмиссии', max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель трансмиссии',
                'verbose_name_plural': 'Модель трансмиссий',
            },
        ),
        migrations.CreateModel(
            name='TypeMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='noname', max_length=255, verbose_name='Название')),
                ('description', models.CharField(default='Вид технического обслуживания', max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид технического обслуживания',
                'verbose_name_plural': 'Виды технических обслуживаний',
            },
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='noname', max_length=255, verbose_name='Название')),
                ('description', models.CharField(default='Сервисная компания', max_length=255, verbose_name='Описание')),
                ('user_link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сервисная компания',
                'verbose_name_plural': 'Сервисные компании',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField(verbose_name='Дата проведения ТО')),
                ('operating_time', models.IntegerField(default=0, verbose_name='Наработка, м/час')),
                ('order_number', models.CharField(max_length=255, verbose_name='Номер заказ-наряда')),
                ('order_date', models.DateField(verbose_name='Дата заказ-наряда')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_book.machine', verbose_name='Машина')),
                ('maintenance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_book.maintenancecompany', verbose_name='Организация, проводившая ТО')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_book.servicecompany', verbose_name='Сервисная компания')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_book.typemaintenance', verbose_name='Вид ТО')),
            ],
            options={
                'verbose_name': 'Техническое обслуживание',
                'verbose_name_plural': 'Технические обслуживания',
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='model_steering_axle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_book.steeringaxle', verbose_name='Модель управляемого моста'),
        ),
        migrations.AddField(
            model_name='machine',
            name='model_transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_book.transmission', verbose_name='Модель трансмиссии'),
        ),
        migrations.AddField(
            model_name='machine',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_book.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refusal_date', models.DateField(verbose_name='Дата отказа')),
                ('operating_time', models.IntegerField(default=0, verbose_name='Наработка, м/час')),
                ('refusal_description', models.TextField(max_length=1000, verbose_name='Описание отказа')),
                ('repair_parts', models.TextField(blank=True, max_length=1000, verbose_name='Используемые запасные части')),
                ('recovery_date', models.DateField(verbose_name='Дата восстановления')),
                ('downtime', models.IntegerField(default=0, verbose_name='Время простоя техники')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_book.machine', verbose_name='Машина')),
                ('recovery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_book.recoverymethod', verbose_name='Способ восстановления')),
                ('refusal_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_book.refusalnode', verbose_name='Узел отказа')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_book.servicecompany', verbose_name='Сервисная компания')),
            ],
            options={
                'verbose_name': 'Рекламация',
                'verbose_name_plural': 'Рекламации',
            },
        ),
    ]
